#!/bin/bash
#Generate front and back AWS CLI JSON input files
jq --arg fl frontListener --arg tg1 $UI_tg1 --arg tg2 $UI_tg2 -n '{"LoadBalancerArn":$fl,"Protocol":"HTTP","Port":0,"DefaultActions":[{"Type":"forward","ForwardConfig":{"TargetGroups":[{"TargetGroupArn":$tg1,"Weight":1},{"TargetGroupArn":$tg2,"Weight":0}],"TargetGroupStickinessConfig":{"Enabled":true,"DurationSeconds":120}}}]}' > createFrontListener.json
jq --arg fl backListener --arg tg1 $API_tg1 --arg tg2 $API_tg2 -n '{"LoadBalancerArn":$fl,"Protocol":"HTTP","Port":0,"DefaultActions":[{"Type":"forward","ForwardConfig":{"TargetGroups":[{"TargetGroupArn":$tg1,"Weight":1},{"TargetGroupArn":$tg2,"Weight":0}],"TargetGroupStickinessConfig":{"Enabled":true,"DurationSeconds":120}}}]}' > createBackListener.json

aws elbv2 create-listener --cli-input-json createFrontListener.json > frontListenerOutput.json
aws elbv2 create-listener --cli-input-json createBackListener.json > backListenerOutput.json

#front listener arn
jq ".Listeners[0].ListenerArn" frontListenerOutput.json -r
#back listener arn
jq ".Listeners[0].ListenerArn" backListenerOutput.json -r

